title: Ankit Kumar Jain
logo: assets/img/Ankit - Image.jpg
description: I am learning machine learning and Artificial intelligence, and have experience in Data.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
