title: Hi🤔, I'm Rouge Li
logo: /assets/img/head.jpg
description: "I'm Rouge Li, a Computer Science student. I'm interested in Computer Architecture.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
