
  
title: <p align="center">Arun Prakash </p>
logo: /assets/img/Screenshot%202022-12-26%20at%2000.42.31.png

description:
  <p align="center">
#  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> 
 # <a href="https://github.com/sajankedia">GitHub</a>
  
 
 </p>


theme: jekyll-theme-minimal
