title: <p align="center"> Subham Srivastava </p>
logo: /assets/img/subham profile picture.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/subham0206">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Worked with TCS at Data Analytics team.
  <br>
  </p>



theme: jekyll-theme-minimal
