title: <p align="center">Arun Prakash </p>
logo: /assets/img/Screenshot%202022-12-26%20at%2000.42.31.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/arun-prakash123/">LinkedIn</a> |
  <a href="https://github.com/arunprakash-01">GitHub</a>
  
  <br>   
  
  I'm customer centric product professional with  experience as a leader of cross-functional teams and as an Individual Contributor
  in Data Science, Big Data Machine learning &complete product life cycle of Digital products.
  Worked with IBM and Barclays Africa at Big Data Analytics team.
 
  <br>
  </p>

theme: jekyll-theme-minimal
