title: Minimal theme
logo: /assets/WhatsApp_Image_2022-06-15_at_9.44.39_PM-removebg-preview.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
