title: <p align="center"> Saurabh Bhargava </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/saurabhbhargava1/">LinkedIn</a> |
  <a href="https://github.com/saurabhbhargava6">GitHub</a>
  
  <br>   
I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
<br>
Working as a Full Stack Web developer for tools website using Python, MySql, Javascript, Bootstrap

  </p>
theme: jekyll-theme-minimal
