title: <p align="center"> Aatir Khursheed Kirmani </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  # <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aatir-kirmani-99886414a/">LinkedIn</a> |
  <a href="https://github.com/aatirkirmani">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
