title: <p align="center"> Shahriar Kabir Khan </p>

logo: "assets/img/logo.png?raw=true"

description:
  <p align="center">
  <a href="assets/pdf/CV-Shahriar Kabir Khan">Resume</a> |
  <a href="https://www.linkedin.com/in/kabiruh19/">LinkedIn</a> |
  <a href="https://github.com/mskabirkhan">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MSc degree in Artificial Intelligence from Queen Mary University of London.
  <br><br>
  I am currently a Data Engineer Intern at Health Data Research UK with a focus on working with large amount health data, data wrangling, visualising, deploying.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
// google_analytics: UA-145578661-1 # Google Analytics tracking ID
