title: Mayuri Satish Debadwar
logo: /assets/img/Mayuri (2).jpg
description: Profile under construction.
<p align="center">
  |
  <a href="https://www.linkedin.com/in/mayuri-debadwar-504b23135/">LinkedIn</a> |
  <a href="https://github.com/mdebadwar">GitHub</a>

  <br>  
  I am working as a Data Analyst from last 2.5 years having experties in 
  SQL, Tableau, Python - (Numpy, Pandas, MatplotLib, Seaborn, Sklearn) 
  Being an enthusiastic data analyst I would like to grow as a Data Scientist.
  Currently working on a project in E-commerce domain to migrate data from legacy systems to cloud using AWS, SQL, Python & PowerBI.
  <br>
 </p>
