title: <p align="Center"> Arun C V </p>
logo: /assets/img/logo.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/arun-cv-kashyap-a6272022/">LinkedIn</a> |
  <a href="https://arun-c-v.github.io/minimal/">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
