title: Executive PG in ML and AI
Profile picture: <img src="/assets/img/new_dp.jpg" width=320px height=320px>
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
