title: Hi🤔, I'm Rouge Li
logo: /assets/img/head.jpg
description: "I am Rouge Li, a Computer Science student. I am interested in Computer Architecture."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
