title: <p align="center"> Subham Srivastava </p>
logo: /assets/img/subham profile picture.jpg

description:
  <p align="center">
  <a href="assets/img/Subham-Srivastava-Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/subham-srivastava-40b5b0149/">LinkedIn</a> |
  <a href="https://github.com/subham0206">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems at Becton Dickinson.
  Worked with TCS at Data Analytics team.
  <br>
  </p>



theme: jekyll-theme-minimal
