title: <p align="center"> Jagadish Kulkarni </p>
logo: /assets/img/logo.png

description:
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time data.
  Worked with ABC Research at Big Data Analytics team.
  Working in ABC domain for 10 years.
  <br>




theme: jekyll-theme-minimal
