name: Custom
url: http://endeavorlabs.net
logo: /assets/img/logo.png
description: The Mad Tinker
permalink: /:title/
show_downloads: true
theme: jekyll-theme-minimal

include:
  - _pages
  - jemoji
  - _posts

paginate: 5

plugins: [jekyll-paginate]
exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]
highlighter: rouge
baseurl: /
