title: Gopalarao
logo: /assets/img/WhatsApp Image 2024-01-02 at 05.16.07_509b0251.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
