title: Tapan Nayak
logo: /assets/img/WhatsApp Image 2024-03-12 at 19.30.55.jpeg
description: Test Specialist | Machine Learning Data Engineer 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
