title: Alice Gadau
logo: "assets/img/image_personal.png"
description: >
  <br><br>
  PhD student at The Rockefeller University. For my evolutionary genetics Phd, I studied how invasive species adapt to new environments
  <br><br>
  Expertise: Evolution / Genomics / Neurobiology
  <br><br>
  <a href="www.linkedin.com/in/alice-gadau-0365ba152">LInkedIn</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins: jekyll-remote-theme 
theme: jekyll-theme-minimal
