title: Alice Gadau
logo: "assets/img/image_personal.png"
description: >
  <br>
  PhD student at The Rockefeller University. For my evolutionary genetics Phd, I studied how invasive species adapt to new environments. I'm excited to apply my skills as a data journalist.
  <br><br>
  Expertise: Evolution / Genomics / Neurobiology / Data Visualization
  <br><br>
  <a href="https://www.linkedin.com/in/alice-gadau-0365ba152/">LInkedIn</a>

theme: jekyll-theme-minimal
