title: <p align="center"> Amar Raj Urs </p>
logo: /assets/img/logo.png
description: 
<p aligns"center"
<a here="https://www.linkedin.com/in/amarajurs/">LinkedIn<a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
