title: 21 Days Refresher Course on Agroforestry
logo: D:\Odrive\sureshramanans01 folder\cafri\Logo\Presentation1-removebg-preview.png
description: The Indian Society of Agroforestry (ISAF) is organising a refresher course for academicians, government officials, Masters’ and Ph.D. students. The objective of the programme is to provide an overview of agroforestry as well as to provide insights on the recent research and development initiatives in the agroforestry. The program is being organized in association with ICAR-CAFRI, Jhansi and supported by the Ministry of Agriculture & Farmers' Welfare, Govt. of India.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
