title: <p align="center"> Garv Daga </p>
logo: /assets/img/Garv_Daga_Passport_Photo.png

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/garv-daga-372649148/">LinkedIn</a> |
  <a href="https://github.com/garvdaga09">GitHub</a>
  
  <br>   
  I'm working on Machine learning related problems.
  Working as a Software Developer in Dell technologies for 4 years.
  <br>
  </p>

theme: jekyll-theme-minimal