title: Ritik Kumar
logo: /assets/img/assets/img/"C:\Users\ritik\OneDrive\Pictures\Saved Pictures\IMG-20221204-WA0041.jpg"
description: Data analyst | ML | Python | Statistics | SQL | Researcher | Student
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
