title: <p align="center">Pat BALDOMAR</p>
logo: /assets/img/Paterno.jpg
description: 
  <p align="center">
  <a href="/assets/img/CV%20VSL%20Paterno%20Baldomar.pdf"><img alt="Static Badge" src="https://img.shields.io/badge/RESUME-8A2BE2"></a> 
  <a href="https://in.linkedin.com/in/patab"><img alt="Static Badge" src="https://img.shields.io/badge/LinkedIn-blue"></a> 
  <a href="/another-page.md"><img alt="Static Badge" src="https://img.shields.io/badge/Data%20Science-black"></a>
  </p>
  <br>
  <p align="center">
  This is my Data Science Portfolio.
  </p>
  <br>
  <p align="justify">
  Took up Data Science Bootcamps and still honing my Python skill.
  </p>
  </br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
