title: Mohit Kumar Dubey
logo: /assets/img/IMG_6416_1.jpg
description: 13+ years | Software Architect at dailyhunt and Josh | Part time trainer - iOS/ Android/ ReactNative/ KMM
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
