title: <p align="center"> Shahriar Kabir Khan </p>

logo: "assets/img/logo.png?raw=true"

description: <p align="center">
  <a href="assets/pdf/CV - Shahriar Kabir Khan.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kabiruh19/">LinkedIn</a> |
  <a href="https://twitter.com/shahriarkabir73">Twitter</a> |
  <a href="https://stackoverflow.com/users/9453613/shahriar-kabir-khan">Stack Overflow</a>
  </p>

  <p align="justify">
  Recently, I have completed my MSc degree in Artificial Intelligence from Queen Mary University of London.
  <br><br>
  Currently, I am working as Data Curator at Health Data Research UK where previously I also completed my one-year industrial experience as Data Engineer Intern, focused on working with large amount health data, data wrangling, visualising, deploying.
  <br><br>
  </p>

theme: jekyll-theme-minimal
// google_analytics: # Google Analytics tracking ID
