title: <p align="center"> Naveen Kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/naveenharry03/">LinkedIn</a> |
  <a href="https://github.com/naveenharry03">GitHub</a>
 
  <br>  
  I'm working on Quality Assurance Engineer with 6 years Experience in Fefundinfo.
  Also Had Exposure on Computer vision
  Done Microsoft AI Fundamentals Certification
  <br>
  </p>



theme: jekyll-theme-minimal
