title: <p align="center"> Saurabh Bhargava </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/saurabhbhargava1/">LinkedIn</a> |
  <a href="https://github.com/saurabhbhargava6">GitHub</a>
  
  <br>   
  <ul>
      <li>Working as a Full Stack Web developer for tools website using Python, MySql, Javascript, Bootstrap </li>
  </ul>

  </p>
theme: jekyll-theme-minimal
