title: Kshitiz Jaiswal
logo: assets/img/299B5AB2-A293-4C82-A30D-D330A39D46B2.heic
description: Solution Architect with 13 years of Experience 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
