title: <p align="center"> Navdeep Chahal </p>
logo: /assets/img/NavdeepChahal.JPEG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/navdeep-chahal-pmp%C2%AE-47aa7821/">LinkedIn</a> |  
  <a href="https://github.com/NavdeepsChahal/">GitHub</a>
  
  <br>   
  I'm working on Data Science and  Machine learning & NLP related problems.
  Working in Insurance domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
