title: Tyler Butler
logo: /assets/img/logo.png
description: Independent Vulnerability Researcher, Deloitte Adversary Simulation & Pentesting 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
