title: <p align="center"> ISHAN BIYANI </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ishan-biyani-310921175/">LinkedIn</a> |
  <a href="https://github.com/Biyani404198">GitHub</a>
  
  <br>   
  I'm working on Data Science and Machine learning related problems.

  <br>
  </p>



theme: jekyll-theme-minimal
