title: <p align="center"> Sheena Mathew </p>
logo: https://github.com/SheenaMathew19/minimal/blob/master/aimlenthu.jpg

description:
  <p align="center">
  <a href="https://github.com/SheenaMathew19">GitHub</a>
  
  <br>   
  Data science Entusiast
  <br>
  </p>
