title: <p align="center"> Saurav Ujjain </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sarv/">LinkedIn</a> |
  <a href="https://github.com/sauravujjain">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
 
  <br>
  </p>

