title: <p align=center> Sindhushree G S </p>
logo: /assets/img/IMG_20211230_172416.jpg
description: I'm working as a Software Engineer in OTSI. I currently work as an Automation Engineer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
