title: Fabrício Macena
logo: /assets/img/me.jpg
description: > 
  <br>
  Estudante em Análise e Desenvolvimento de Sistemas e focando os estudos em Ciência de Dados. 
  <br><br>
  <a href="https://www.linkedin.com/in/fabriciomacena/">Veja meu perfil no LinkdIn</a>

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal