title: Minimal theme
logo: /assets/img/"C:\Users\admin\Desktop\personal-documents\822f0cc6-4232-4170-8cd6-6d4436a62cf0.jpg"
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
