logo: /assets/img/logo.png
title: Victor Hugo Vital de Souza
description: em construção
logo: [Location of the logo]
show_downloads: false
google_analytics: [em construção]
theme: jekyll-theme-minimal



