title: Welcome to my Data Science portfolio.
logo: /assets/img/pic.png
description: Data Scientist/Analyst with experiences in USA, Japan, and Singapore.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
