title: Anjali Rani
logo: /assets/img/resizePic_97KB.jpg
description: 4 years experienced RPA developer equipped with great coding, debugging and Project Managementabilities. Accomplishes project goal consistently with elegant, scalable code under Agile and scrumframeworks.
Flexible and focused on boosting effi ciency and performance with conscientious anddetail-oriented approaches. Eager to apply extensive knowledge to achieve company goals anddedicated to make positive contributions.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
